// Render an isolated, synthetic admin fixture generated by AdminTablesTest.
import http from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';

const root = path.resolve(import.meta.dirname, '..');
const out = path.join(root, 'storage/framework/admin-preview');
await mkdir(out, { recursive: true });
const mime = { '.css': 'text/css', '.js': 'application/javascript', '.html': 'text/html', '.woff': 'font/woff', '.woff2': 'font/woff2', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.gif': 'image/gif', '.ttf': 'font/ttf', '.eot': 'application/vnd.ms-fontobject' };
const server = http.createServer(async (request, response) => {
    try {
        const pathname = new URL(request.url, 'http://localhost').pathname;
        if (pathname === '/admin/chat/notifications') {
            response.setHeader('Content-Type', 'application/json');
            response.end('{"items":[],"count":0}');
            return;
        }
        if (pathname === '/admin/dosen') {
            response.setHeader('Content-Type', 'text/html; charset=utf-8');
            let html = await readFile(path.join(root, 'storage/framework/admin-preview.html'), 'utf8');
            html = html.replace(/http:\/\/\[::1\]:5173\//g, 'http://127.0.0.1:18767/');
            html = html.replace(/<script type="module" src="http:\/\/127.0.0.1:18767\/@vite\/client"><\/script>/g, '');
            response.end(html);
            return;
        }
        if (pathname === '/@vite/client') {
            response.setHeader('Content-Type', 'application/javascript');
            response.end('export default {};');
            return;
        }
        const file = path.resolve(root, '.' + decodeURIComponent(pathname));
        const ext = path.extname(file);
        if (!file.startsWith(root + path.sep) || !/^(?:\/(?:build|vendors|css|js|images|fonts|resources))\//.test(pathname) || !mime[ext]) {
            response.writeHead(404).end(); return;
        }
        if (!(await exists(file))) {
            response.setHeader('Content-Type', mime[ext]);
            if (ext === '.svg') response.end('<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"></svg>');
            else response.end(Buffer.alloc(0));
            return;
        }
        response.setHeader('Content-Type', mime[ext]);
        response.end(await readFile(file));
    } catch { response.writeHead(404).end(); }
});

async function exists(file) {
    try { await readFile(file); return true; } catch { return false; }
}
await new Promise(resolve => server.listen(18767, '127.0.0.1', resolve));
const chrome = spawn(process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', [
    '--headless=new', '--no-first-run', '--no-default-browser-check', '--disable-gpu',
    '--remote-debugging-port=18768', '--user-data-dir=' + path.join(out, 'chrome-profile'), 'about:blank',
], { windowsHide: true, stdio: 'ignore' });
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
let socket;
try {
    let tab;
    for (let attempt = 0; attempt < 80; attempt++) {
        try { tab = (await (await fetch('http://127.0.0.1:18768/json', { signal: AbortSignal.timeout(500) })).json()).find(item => item.type === 'page'); if (tab) break; }
        catch { /* Wait for the local browser to start. */ }
        await delay(100);
    }
    if (!tab) throw new Error('Chrome did not start.');
    socket = new WebSocket(tab.webSocketDebuggerUrl);
    await new Promise(resolve => socket.addEventListener('open', resolve, { once: true }));
    let id = 0;
    const pending = new Map(), errors = [];
    socket.addEventListener('message', event => {
        const data = JSON.parse(event.data);
        if (data.id) { const call = pending.get(data.id); pending.delete(data.id); data.error ? call.reject(data.error) : call.resolve(data.result); }
        if (data.method === 'Runtime.exceptionThrown') errors.push(data.params.exceptionDetails.text);
        if (data.method === 'Network.responseReceived' && data.params.response.url.startsWith('http://127.0.0.1:18767/') && data.params.response.status >= 400) errors.push(data.params.response.url);
    });
    const send = (method, params = {}) => new Promise((resolve, reject) => { const key = ++id; pending.set(key, { resolve, reject }); socket.send(JSON.stringify({ id: key, method, params })); });
    const evaluate = async expression => {
        const value = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
        if (value.exceptionDetails) throw new Error(JSON.stringify(value.exceptionDetails));
        return value.result.value;
    };
    await send('Page.enable'); await send('Runtime.enable'); await send('Network.enable');
    await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1040, deviceScaleFactor: 1, mobile: false });
    await send('Page.navigate', { url: 'http://127.0.0.1:18767/admin/dosen' });
    for (let attempt = 0; attempt < 150; attempt++) {
        if (await evaluate('!!document.querySelector(\'input[name="dosen_search"]\') && document.readyState !== "loading"')) break;
        await delay(200);
    }
    await evaluate('Promise.race([document.fonts.ready.then(() => true), new Promise(resolve => setTimeout(() => resolve(false), 5000))])');
    const desktop = await evaluate(`({ fonts: [...document.fonts].filter(f => f.family.includes('Awesome')).map(f => ({ family:f.family, status:f.status })), overflow: document.documentElement.scrollWidth > innerWidth, search: !!document.querySelector('input[name="dosen_search"]'), rows: document.querySelectorAll('table tbody tr').length, menuActive: document.querySelectorAll('#sidebar [aria-current="page"]').length })`);
    await writeFile(path.join(out, 'desktop.png'), Buffer.from((await send('Page.captureScreenshot', { format: 'png' })).data, 'base64'));
    if (desktop.overflow || !desktop.search || desktop.menuActive !== 1 || !desktop.fonts.some(f => f.status === 'loaded')) throw new Error('Desktop checks failed: ' + JSON.stringify(desktop));
    await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
    await delay(500);
    const mobile = await evaluate(`({ overflow: document.documentElement.scrollWidth > innerWidth, sidebarHidden: !!document.getElementById('sidebar') && document.getElementById('sidebar').inert })`);
    await writeFile(path.join(out, 'mobile.png'), Buffer.from((await send('Page.captureScreenshot', { format: 'png' })).data, 'base64'));
    await evaluate(`document.querySelector('[data-admin-menu="mobile"]').click()`);
    const menuOpen = await evaluate(`document.body.classList.contains('admin-sidebar-open') && !!document.getElementById('sidebar') && !document.getElementById('sidebar').inert`);
    await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 });
    const menuClosed = await evaluate(`!document.body.classList.contains('admin-sidebar-open') && !!document.getElementById('sidebar') && document.getElementById('sidebar').inert`);
    if (mobile.overflow || !mobile.sidebarHidden || !menuOpen || !menuClosed) throw new Error('Mobile checks failed: ' + JSON.stringify({ mobile, menuOpen, menuClosed }));
    console.log(JSON.stringify({ desktop, mobile, menuOpen, menuClosed, errors }, null, 2));
    if (errors.length) throw new Error('Browser errors detected.');
    await send('Browser.close');
} finally {
    socket?.close();
    chrome.kill();
    server.close();
}
